---
  dependencies:
    - role: geerlingguy.mac.mas
      vars:
        mas_installed_apps:
          - id: 907364780
            name: Tomato One
          - id: 1335413823
            name: Ka-block!
          - id: 747648890
            name: Telegram
          - id: 409183694
            name: Keynote