---
  - name: Add required homebrew repos
    homebrew_tap:
      name: homebrew/cask-fonts

  - name: Ensure console utils are installed
    homebrew:
      name:
        - ansible-lint
        - asimov
        - bat
        - bfg
        - dive
        - dog
        - exa
        - fd
        - gh
        - git
        - git-delta
        - gnupg
        - hadolint
        - httpie
        - jsonlint
        - lima
        - mtr
        - nmap
        - openssl
        - pinentry-mac
        - pv
        - ripgrep
        - siege
        - sloccount
        - sqlite
        - telnet
        - yamllint

  - name: Ensure graphical utils are installed
    homebrew_cask:
      name:
        - font-martian-mono
        - font-sauce-code-pro-nerd-font
        - ngrok

  - name: Ensure node utils are installed
    homebrew:
      name:
        - nodejs